databases:
  - name: consulting-notifications-db
    databaseName: consulting_notifications
    plan: free

services:
  - type: web
    name: consulting-notifications
    runtime: docker
    plan: free   # 👈 isso garante que é 100% free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: consulting-notifications-db
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
