default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: consulting_notifications_development

test:
  <<: *default
  database: consulting_notifications_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    # Opcional: ajuste pool se precisar
    # pool: 5