# Simplificado para evitar fallback em socket local em produção
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: consulting_notifications_development

test:
  <<: *default
  database: consulting_notifications_test

production:
  <<: *default
  # Render injeta DATABASE_URL automaticamente se usar blueprint ou se você definir no painel
  url: <%= ENV["DATABASE_URL"] %>
  # Evita qualquer tentativa de socket se a URL estiver presente
  host: <%= URI(ENV["DATABASE_URL"]).host if ENV["DATABASE_URL"] %>
  # Caso queira SSL explícito (se Render exigir explicitamente):
  # variables:
  #   sslmode: require