default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: consulting_notifications_development

test:
  <<: *default
  database: consulting_notifications_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # Se quiser forçar prepared statements off (às vezes em Render com conexões pequenas):
  # prepared_statements: false