default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  connect_timeout: 10
  checkout_timeout: 10

development:
  <<: *default
  database: consulting_notifications_development

test:
  <<: *default
  database: consulting_notifications_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>